### ISSUE TITLE
Deadline

### ISSUE THREAD

**Issue by raghavgoyal14** [hudaAlamri/DSTC7-Audio-Visual-Scene-Aware-Dialog-AVSD-Challenge#1]
Hi,

I'm a bit confused regarding when can make submissions and what's the deadline for the challenge.
Link: http://workshop.colips.org/dstc7/dates.html

Can we make submissions until the end of development phase or evaluation phase?

Thanks in advance,
Raghav

**Comment by dialogtekgeek** [comment]
The submission can be done from Sep 24th to Oct 1st.
The submission web will be open on Sep.24th.

**Comment by raghavgoyal14** [comment]
Thanks for the details
